# Generated by Django 4.2.1 on 2023-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_tray_detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='jumlah',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(default=1, upload_to='memory_tray_detector'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip_camera',
            field=models.IntegerField(null=True),
        ),
    ]
