# Generated by Django 4.2.1 on 2023-05-22 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memory_tray_detector', '0002_gallery_jumlah_gallery_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='jumlah',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='gallery',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
