# Generated by Django 4.2.1 on 2023-05-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_tray_detector', '0008_alter_gallery_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camcard',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
