# Generated by Django 4.2.1 on 2023-05-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_tray_detector', '0011_alter_camera_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip_camera',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
