# Generated by Django 4.2.1 on 2023-05-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memory_tray_detector', '0012_alter_camera_ip_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory_tray_detector.camera')),
            ],
        ),
    ]
