# Generated by Django 4.2.1 on 2023-05-29 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memory_tray_detector', '0014_listcamera_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='detected_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
