# Generated by Django 4.2.1 on 2023-05-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_detector', '0004_alter_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nrp',
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
