# Generated by Django 4.2.1 on 2023-05-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_detector', '0006_detectedface_alter_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
