# Generated by Django 4.2.1 on 2023-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_detector', '0009_alter_detectedface_detected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedface',
            name='detected_time',
            field=models.DateTimeField(),
        ),
    ]
