# Generated by Django 4.2.1 on 2023-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_detector', '0010_alter_detectedface_detected_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='full_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
