# Generated by Django 4.2.1 on 2023-05-18 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person_detector', '0012_rename_full_name_post_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedface',
            name='detected_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
