# Generated by Django 4.2.1 on 2023-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_detector', '0013_detectedface_detected_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='person_detector'),
        ),
    ]
