# Generated by Django 4.2.1 on 2023-05-31 00:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trash_can_detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='detected_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(null=True, upload_to='trash_can_detector'),
        ),
        migrations.CreateModel(
            name='ListCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='trash_can_detector')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash_can_detector.camera')),
            ],
        ),
    ]
